image: gitpod/workspace-full

tasks:
  - init: Install Apache Server
    command: |
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo systemctl start apache2
      sudo systemctl enable apache2
  - init: Install PHP
    command: |
      sudo apt-get install -y php libapache2-mod-php
      sudo systemctl restart apache2
  - init: Install MySQL
    command: |
      sudo apt-get install -y mysql-server
      sudo mysql_secure_installation
  - init: Install PHPMyAdmin
    command: |
      sudo apt-get install -y phpmyadmin
      echo 'Include /etc/phpmyadmin/apache.conf' | sudo tee -a /etc/apache2/apache2.conf
      sudo systemctl restart apache2
  - init: Install Composer
    command: |
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      php -r "unlink('composer-setup.php');"
  - init: Install Node.js and npm
    command: |
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
  - init: Install Git
    command: |
      sudo apt-get install -y git
  - init: Install Redis
    command: |
      sudo apt-get install -y redis-server
      sudo systemctl enable redis-server.service
      sudo systemctl start redis-server.service
  - init: Install Python and pip
    command: |
      sudo apt-get install -y python3 python3-pip

ports:
  - name: webserver
    port: 80
    onOpen: open-preview
    visibility: public