image: gitpod/workspace-full

tasks:
      - name: Start Apache
        init: |
          sudo apt-get update
          sudo apt-get install -y apache2
        before: |
          sudo systemctl enable apache2
          sudo systemctl start apache2
        command: |
          sudo systemctl status apache2

ports:
  - name: apache
    port: 80
    onOpen: open-preview
    visibility: public